### ISSUE TITLE
访问比github源站还慢

### ISSUE THREAD

**Issue by githubusera2034324** [kgithub666/kgithub#11]
加个cdn吧哥，couldflare的都是免费的

**Comment by kgithub666** [comment]
1.本意是为无法访问的客户或访问效果不佳的用户提供加速，觉得比源站慢您可以直接用源站。
2.若您觉得cloudflare的免费版本能满足你的需求，您可自行搭建，此方面教程很多
3.因各家运营商对跨境线路的优化良莠不齐，已公开[所有主站IP](https://status.kkgithub.com/status/kgithub)，可自行拨测，择优选择。

**Comment by githubusera2034324** [comment]
问题已解决
