### ISSUE TITLE
在项目的`code`视图中是如何做到`github.com`更改为`kgithub.com`？

### ISSUE THREAD

**Issue by UlinoyaPed** [kgithub666/kgithub#2]
在项目的`README.md`中如果有一个链接或图片的`src`中出现了`github.com`，那么就会转变成`kgithub.com`

例`https://github.com/cli/cli`预览时就会变成`https://kgithub.com/cli/cli`

请问这是如何做到的？

**Comment by YiZhiXiaoLiuLang** [comment]
全局替换？
